config/routes.rb
Rails.application.routes.draw do
  resources :userdetails
  resources :teams
  resources :companies
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

	has_many :teams
	
	mount_uploader :logoimg, CompanylogoUploader

	def country_name
	   countryname = ISO3166::Country[country]
	   countryname.translations[I18n.locale.to_s] || country.name
	end
	
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :company

  belongs_to :owner,  :class_name=>'User', :foreign_key=>'owner_id'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable, :timeoutable, :trackable,
         :recoverable, :rememberable, :validatable

  has_one :userdetail
end

app/models/userdetail.rb
class Userdetail < ApplicationRecord

	mount_uploader :usrphoto, LogousrUploader

  belongs_to :user
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.where("id > 0")
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :website, :email, :industry, :phone, :address, :zipcode, :logoimg, :country, :profile, :emailmng)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :department, :company_id, :owner_id)
    end
end

app/controllers/userdetails_controller.rb
class UserdetailsController < ApplicationController
  before_action :set_userdetail, only: [:show, :edit, :update, :destroy]

  # GET /userdetails
  # GET /userdetails.json
  def index
    @userdetails = Userdetail.all
  end

  # GET /userdetails/1
  # GET /userdetails/1.json
  def show
  end

  # GET /userdetails/new
  def new
    @userdetail = Userdetail.new
  end

  # GET /userdetails/1/edit
  def edit
  end

  # POST /userdetails
  # POST /userdetails.json
  def create
    @userdetail = Userdetail.new(userdetail_params)

    respond_to do |format|
      if @userdetail.save
        format.html { redirect_to @userdetail, notice: 'Userdetail was successfully created.' }
        format.json { render :show, status: :created, location: @userdetail }
      else
        format.html { render :new }
        format.json { render json: @userdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userdetails/1
  # PATCH/PUT /userdetails/1.json
  def update
    respond_to do |format|
      if @userdetail.update(userdetail_params)
        format.html { redirect_to @userdetail, notice: 'Userdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @userdetail }
      else
        format.html { render :edit }
        format.json { render json: @userdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userdetails/1
  # DELETE /userdetails/1.json
  def destroy
    @userdetail.destroy
    respond_to do |format|
      format.html { redirect_to userdetails_url, notice: 'Userdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userdetail
      if Userdetail.where(:id=> params[:id]).count == 0
        @userdetail = Userdetail.new
      else
        @userdetail = Userdetail.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userdetail_params
      params.require(:userdetail).permit(:user_id, :team_id, :name, :phone, :address, :usrphoto)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/userdetails_helper.rb
module UserdetailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true, :html=>{:multipart => true} ) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="col-sm">

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label :website %>
        <%= form.text_field :website, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label :industry %>
        <%= form.text_field :industry, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.text_field :phone, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_area :address, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label :zipcode %>
        <%= form.text_field :zipcode, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label :country %>
        <%= form.country_select :country, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :profile %>
        <%= form.text_area :profile, class: "form-control form-control-sm" %>
      </div>

      <div class="form-group">
        <%= form.label "Upload Company Logo" %>
        <%= form.file_field :logoimg, class: "btn btn-info" %>
      </div>

      <div class="form-group">
        <%= form.label "Manager Email" %>
        <%= form.text_field :emailmng, class: "form-control form-control-sm" %>
      </div>

      <div class="actions">
        <%= form.submit "Send", :class=>"btn btn-danger" %>
      </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
<% end %>

<br>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company, :class=>"btn btn-primary" %> |
<%= link_to 'Back', companies_path, :class=>"btn btn-secondary" %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

  <div class="list-group">
    <% @companies.each do |company| %>
        <%= link_to image_tag(company.logoimg.thumb.url.to_s) + " Company: " + company.name + "   -   email: " + company.email, company_path(company), :class=>"list-group-item list-group-item-action" %>
    <% end %>
  </div>
<br>

<%= link_to 'New Company', new_company_path, :class=>"btn btn-success" %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path, :class=>"btn btn-secondary" %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm">
    <p>
      <h1>
        <strong>Name:</strong>
        <%= @company.name %><br/>
        <%= image_tag @company.logoimg_url.to_s %>
      </h1>
    </p>
  </div>

  <div class="col-sm compshow">
    <p>
      <strong>Website:</strong>
      <%= @company.website %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @company.email %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @company.phone %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @company.address %>
    </p>

    <p>
      <strong>Zipcode:</strong>
      <%= @company.zipcode %>
    </p>

    <p>
      <strong>Country:</strong>
      <%= @company.country_name %>
    </p>

    <p>
      <strong>Industry:</strong>
      <%= @company.industry %>
    </p>

    <p>
      <strong>Profile:</strong>
      <%= @company.profile %>
    </p>

    <p>
      <strong>Manager Email:</strong>
      <%= @company.emailmng %>
    </p>

  </div>
</div>



<%= link_to 'Edit', edit_company_path(@company),:class=>"btn btn-warning" %> |
<%= link_to 'Teams', teams_path(@company),:class=>"btn btn-info" %> |
<%= link_to 'Back', companies_path,:class=>"btn btn-secondary" %>

app/views/layouts/_footer.html.erb
<div class="container-fluid pie">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="row">
					<div class="col-4">
						<%= image_tag("CGSlogo.png", size:"71x32") %>
					</div>
					<div class="col-8">
						COMPAÑIA GENERAL<br/>DE SERVICIOS SRL
					</div>
				</div>
			</div>

			<div class="col">
				<div class="row">
					<div class="col-3">
						<%= image_tag("home.png") %>
					</div>
					<div class="col-9">
						Los Zorzales 620 - Juana Koslay<br/>Prov de San Luis - CP: 5701
					</div>
				</div>
			</div>

			<div class="col">
				<div class="row">
					<div class="col-3">
						<%= image_tag("phone.png") %>
					</div>
					<div class="col-9">
						J Pina: +54 9 266(15)4512645<br/>G Falavigna: +54 9 266(15)4512644
					</div>
				</div>
			</div>

			<div class="col">
				<div class="row">
					<div class="col-3">
						<%= image_tag("mail.png") %>
					</div>
					<div class="col-9">
						J Pina: <a href="mailto:pinajoa@yahoo.com">pinajoa@yahoo.com</a><br/>G Falavigna: <a href="mailto:gfalav@hotmail.com"> gfalav@hotmail.com</a>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <a class="nav-link" href="/"><%= image_tag("CGSlogo.png", size:"78x35") %></a>
  <a class="navbar-brand" href="/">CGPROYS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if (user_signed_in?) %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Dashboard</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Projects</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Companies" , companies_path, :class=>"dropdown-item" %>
            <%= link_to "Teams" , teams_path, :class=>"dropdown-item" %>
            <%= link_to "People" , userdetails_path, :class=>"dropdown-item" %>
          </div>
        </li>      
        <li class="nav-item active">
          <a class="nav-link" href="#">Calendar</a>         
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Messages</a>         
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Chat</a>         
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Project</a>
            <a class="dropdown-item" href="#">Task</a>
            <a class="dropdown-item" href="#">Milestone</a>
          </div>
        </li>      
      </ul>
      <div class="dropdown user">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag('user.png', :size=>'30x30') %>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class=>"dropdown-item" %>
            <%= link_to "Change Pwd", edit_user_registration_path, :class=>"dropdown-item" %>
            <%= link_to "Setting", edit_userdetail_path(current_user), :class=>"dropdown-item" %>
        </div>
      </div>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZeusRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">

  </head>

  <body>
    
    <%= render "layouts/topbar" %>

    <div class="principal container">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/userdetails/_form.html.erb
<%= form_with(model: userdetail, local: true) do |form| %>
  <% if userdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userdetail.errors.count, "error") %> prohibited this userdetail from being saved:</h2>

      <ul>
      <% userdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h3><%= label_tag current_user.email %></h3>
    <%= form.hidden_field :user_id, value: current_user.id  %>
  </div>

  <div class="form-group">
    <%= form.label :team_id %>
    <%= form.collection_select(:team_id, Team.all, :id, :name, {include_blank: false}, {class: 'form-control '}) %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control form-control-sm"  %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control form-control-sm"  %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control form-control-sm"  %>
  </div>

  <div class="form-group">
    <%= form.label "Usr photo" %>
    <%= form.file_field :usrphoto, class: "btn btn-info" %>
  </div>

  <div class="actions">
    <%= form.submit "Send", class: "btn btn-danger" %>
  </div>
<% end %>

<br>

app/views/userdetails/edit.html.erb
<h1>Editing User detail</h1>

<%= render 'form', userdetail: @userdetail %>

<%= link_to 'Show', @userdetail, class: "btn btn-primary" %> |
<%= link_to 'Back', userdetails_path, class: "btn btn-secondary" %>

app/views/userdetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

  <div class="list-group"> 
    <% @userdetails.each do |userdetail| %>
        <%= link_to image_tag(userdetail.usrphoto.thumb.url.to_s) + ' ' +userdetail.name + ' - (' + userdetail.user.email + ') from Team: ' + userdetail.team.name, userdetail_path(userdetail), :class=>"list-group-item list-group-item-action" %>
    <% end %>
  </div>

<br>

<%= link_to 'New Userdetail', new_userdetail_path, class: "btn btn-primary" %>

app/views/userdetails/new.html.erb
<h1>New Userdetail</h1>

<%= render 'form', userdetail: @userdetail %>

<%= link_to 'Back', userdetails_path, class: "btn btn-secondary" %>

app/views/userdetails/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm">
    <%= image_tag(@userdetail.usrphoto_url.to_s) %><br>
    <h1>
      <%= @userdetail.name %>  
    </h1>    
  </div>
  <div class="col-sm compshow">
    <h2>User Info</h2>
    <p>
      <strong>User:</strong>
      <%= @userdetail.user.email %>
    </p>
    <p>
      <strong>Team:</strong>
      <%= @userdetail.team.name %>
    </p>
    <p>
      <strong>Phone:</strong>
      <%= @userdetail.phone %>
    </p>
    <p>
      <strong>Address:</strong>
      <%= @userdetail.address %>
    </p>
  </div>
  
</div>

<%= link_to 'Edit', edit_userdetail_path(@userdetail), class: "btn btn-warning" %> |
<%= link_to 'Back', userdetails_path, class: "btn btn-secondary" %>

app/views/welcome/index.html.erb
<div class="home">
	
<h1>Welcome to CGPROYS</h1>
	<p>Aplicación para la gestión de proyectos </p>


	<% if !current_user %>

		<%= link_to "Please LOGIN", new_user_session_path %>
		<br/>
		or click
		<%= link_to "HERE", new_user_registration_path %>
		if you are not registered <br/>
		<%= link_to "Forgot your password?", new_user_password_path %><br />
	<% end %>
</div>